# mezora theme - sauce for macchina cli

separator = "❯"
separator_color = "#e1bdc9"
key_color = "#ffb0d0"
prefer_small_ascii = true

[palette]
type = "Dark"
visible = false
glyph = " ⬤ "

[box]
title = " Astro "
border = "plain"
visible = true


[randomize]
key_color = false
separator_color = false

[custom_ascii]
color = "#ffb0d0"
path = "~/.config/macchina/themes/archlogo.txt"
