[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-step", "10", "--transition-fps", "144"]
set = true


[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk3.css'
output_path = '~/.local/share/themes/Material/gtk-3.0/gtk.css'
post_hook = "gsettings set org.gnome.desktop.interface gtk-theme ''; gsettings set org.gnome.desktop.interface gtk-theme Material; echo 'refreshed gtk'"

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk4.css'
output_path = '~/.local/share/themes/Material/gtk-4.0/gtk.css'
post_hook = "gsettings set org.gnome.desktop.interface gtk-theme ''; gsettings set org.gnome.desktop.interface gtk-theme Material; echo 'refreshed gtk'"

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

#0 - background
#10 - accent primary
#13 - accent secondary
#15 - text

[templates.iconchange]
input_path = '~/.config/matugen/templates/icon_color_input.txt'
output_path = '~/Documents/Scripts/icon_color_input.txt'
post_hook = "~/Documents/Scripts/icon_color_change.sh; gsettings set org.gnome.desktop.interface color-scheme ''; gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"

[templates.zed]
input_path = '~/.config/matugen/templates/zed.json'
output_path = '~/.config/zed/themes/material.json'

[templates.vesktop]
input_path = '~/.config/matugen/templates/discord.css'
output_path = '~/.config/vesktop/themes/material.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'
