

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

monitorv2 {
  output = DP-1
  mode = 2560x1440@360
  position = 0x0
  transform = 0
  vrr = off
}


monitorv2 {
  output = DP-2
  mode = 1920x1080@144
  position = -1080x-360
  scale = auto
  transform = 3
}


#Bind workspace to monitors
workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-3 
