# Font
font_family      CaskaydiaMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11

# Window
window_padding_width 20
background_opacity 0.95

# Cursor
cursor_trail 1

# Preferences
confirm_os_window_close 0


cursor {{colors.on_surface.default.hex}}
cursor_text_color {{colors.on_surface_variant.default.hex}}

foreground            {{colors.on_surface.default.hex}}
background            {{colors.surface.default.hex}}
selection_foreground  {{colors.on_secondary.default.hex}}
selection_background  {{colors.primary_container.default.hex}}
url_color             {{colors.primary.default.hex}}

color0   {{base16.base00.default.hex}}
color1   {{colors.red.default.hex}}
color2   {{colors.green.default.hex}}
color3   {{colors.yellow.default.hex}}
color4   {{colors.blue.default.hex}}
color5   {{colors.magenta.default.hex}}
color6   {{colors.cyan.default.hex}}
color7   {{base16.base06.default.hex}}

color8   {{base16.base03.default.hex}}
color9   {{colors.red.default.hex}}
color10  {{colors.green.default.hex}}
color11  {{colors.yellow.default.hex}}
color12  {{colors.blue.default.hex}}
color13  {{colors.magenta.default.hex}}
color14  {{colors.cyan.default.hex}}
color15  {{base16.base07.default.hex}}
